_target_: diffusion_policy.workspace.train_classifier_image_workspace.TrainClassifierImageWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt
    k: 50
    mode: min
    monitor_key: val_loss
dataloader:
  batch_size: 1024
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
dataset_obs_steps: 2
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: ${now:%Y.%m.%d.%H.%M.%S}_train_classifier
  mode: online
  name: train_classifier
  project: diffusion_policy_debug
  resume: false
  tags:
  - train_classifier
  - square_image
  - default
multi_run:
  run_dir: data/outputs/2025.01/train_classifier
  wandb_name_base: train_classifier
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_classifier
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_classifier_image_policy.DiffusionClassifierImagePolicy
  cond_predict_scale: true
  crop_shape:
  - 76
  - 76
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder:
    _target_: diffusion_policy.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta:
      action:
        shape:
        - 7
      obs:
        language_goal:
          shape:
          - 512
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        robot0_agentview_right_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        robot0_agentview_left_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb    
    rgb_model:
      _target_: diffusion_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: IMAGENET1K_V1 # or r3m
    resize_shape: [128, 128]
    crop_shape: [126, 126]
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
  shape_meta:
    action:
      shape:
      - 7
    obs:
      language_goal:
        shape:
        - 512
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
      robot0_agentview_right_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
      robot0_agentview_left_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
shape_meta:
  action:
    shape:
    - 7
  obs:
    language_goal:
      shape:
      - 512
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    robot0_agentview_right_image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    robot0_agentview_left_image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
task:
  abs_action: false
  balance_dataset: false
  dataset:
    _target_: diffusion_policy.dataset.robocasa_replay_image_dataset.RobocasaReplayImageDataset
    abs_action: false
    dataset_path: data/robomimic/datasets/square/ph/image_abs.hdf5
    horizon: 16
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 7
      obs:
        language_goal:
          shape:
          - 512
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        robot0_agentview_right_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
        robot0_agentview_left_image:
          shape:
          - 3
          - 128
          - 128
          type: rgb
    use_cache: true
    val_ratio: 0.2
  dataset_path: data/robomimic/datasets/square/ph/image_abs.hdf5
  dataset_type: ph
  name: square_image
  shape_meta:
    action:
      shape:
      - 7
    obs:
      language_goal:
        shape:
        - 512
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
      robot0_agentview_right_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
      robot0_agentview_left_image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
  task_name: square
task_name: square_image
training:
  checkpoint_every: 2
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8001
  resume: false
  rollout_every: 50
  sample_every: 50
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 1024
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
